### ISSUE TITLE
Folgende Abhängigkeiten fehlen: "mpdf/mpdf": "^8.0"

### ISSUE THREAD

**Issue by Benjamin-Scherf** [heimrichhannot/contao-pdf-creator-bundle#1]
**Context**
Contao version: 4.9.13
Bundle version: 0.2.1
PHP version: 7.4

Nach Erstinstallation und Auswahl von mPDF erscheint folgender Fehler:
Es fehlen notwendige Abhängigkeiten für die PDF-Bibliothek. Folgende Abhängigkeiten fehlen: "mpdf/mpdf": "^8.0"

**Comment by koertho** [comment]
Das ist korrekt, siehe README. Das Bundle sowie die zugrunde liegende Bibliothek sind bewusst Bibliothek-Unabhängig gebaut.
