### ISSUE TITLE
An exception occurred while executing 'UPDATE tl_article SET `pdfConfiguration`='1' WHERE

### ISSUE THREAD

**Issue by Benjamin-Scherf** [heimrichhannot/contao-pdf-creator-bundle#2]
**Context**
Contao version: 4.9.13
Bundle version: 0.2.1
PHP version: 7.4

Bei der Auswahl der Artikel-Syndikation / PDF-Konfiguration wird folgender Fehler angezeigt:

An exception occurred while executing 'UPDATE tl_article SET `pdfConfiguration`='1' WHERE

**Comment by koertho** [comment]
Hast du nach dem Anpassen der Konfiguration (config.yml) nochmal die die Datenbank geupdated? Falls ja, kannst du bitte einen Screenshot der Fehlermeldung im Dev-Modus posten?
