### ISSUE TITLE
Using the bundle in own extension

### ISSUE THREAD

**Issue by Matt23a** [heimrichhannot/contao-pdf-creator-bundle#5]
What do I have to do to use the pdf creator in my own Contao extension?

When I do it like described in the README, I get the following error:

`request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function generate() on null"`

Do I have to initialize the pdfGenerator somehow?

**Comment by koertho** [comment]
Sure, you need to inject the PdfGenerator service.

**Comment by koertho** [comment]
See this as example: https://github.com/heimrichhannot/contao-pdf-creator-bundle/blob/main/src/EventListener/Contao/PrintArticleAsPdfListener.php
